name: WEB
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: [closed] # when PR closed
    branches: [ main ]
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs ssh deploy for CI, CD
    - name: executing remote ssh commands using password
      if: github.event_name == 'pull_request'
      run: |
        echo ${{ secrets.HOST }}
        echo ${{ secrets.USERNAME }}
        echo ${{ secrets.KEY }}
      #uses: appleboy/ssh-action@master
      #with:
      #  host: ${{ secrets.HOST }}
      #  username: ${{ secrets.USERNAME }}
      #  key: ${{ secrets.KEY }}
        # password: ${{ secrets.PASSWORD }}
        # port: ${{ secrets.PORT }} # default : 22
      #  script: |
      #      cd /home/${{ secrets.USERNAME }}/git/git-action-test
      #      git pull https://${{ secrets.TOKEN }}@github.com/Limyoonsu/git-action-test.git
