name: Android CI

on:
  pull_request:
    types: [closed] # when PR closed
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    
    env:
      SUPER_SECRET : ${{ secrets.HOST }}

    steps:
     - if: github.event_name == 'pull_request'
     - run: echo $SUPER_SECRET
