name: Flask App deploy
# 이벤트 바인딩 : main 브랜치에 push 이벤트 발생 시 실행
on:
  push:
    branches: 
    - main

jobs:
  deploy:
    name: Flask App deploy from NCP server
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /usr/local
          sudo git clone https://github.com/Limyoonsu/git-action-test.git

